target:
	mpicc -g hw1_mpi.c -o "hw1_mpi" -DDATA_TYPE=float  -DDIM=4096 -std=c99 -O3 -funroll-all-loops -floop-block
	gcc hw1.c -o "hw1" -DDATA_TYPE=float -DDIM=4096 -std=c99 -O3 -funroll-all-loops -floop-block
