all: cuda
	@echo ===========================================
	@echo this is the cuda version of program
	@echo u can execute the program like this:
	@echo ./GEC.out 4096
	@echo ===========================================
cuda:
	nvcc GEC.cu -O2 -o GEC.out
