all: Pthreads
	@echo ===================================
	@echo   here is the pthread version
	@echo   run like ./GEP 4096 32
	@echo   the first parameter is the size
	@echo   the second is the max threads
	@echo ===================================
Pthreads:
	gcc GEpthread.c -lpthread -O2 -o GEP
